trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install and build'

- task: Docker@2
  inputs:
    containerRegistry: 'docker'
    repository: 'thsre/node-app'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'deploy-aws-ecs'
    scannerMode: 'CLI'
    configMode: 'file'
    extraProperties: 'sonar.projectKey=node-app'

- task: trivy@1
  inputs:
    version: 'latest'
    path: '$(Build.SourcesDirectory)'

- task: SonarQubeAnalyze@5
  inputs:
    jdkversion: 'JAVA_HOME_11_X64'