trigger:
- main

pool: myAgentPool

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install and build'
- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'sonarqube'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'deploy-aws-ecs_deploy-aws-ecs_AY9oDafPz9YFo-a53DRH'
    cliProjectName: 'deploy-aws-ecs'
    cliSources: '.'
- task: SonarQubeAnalyze@5
  inputs:
    jdkversion: 'JAVA_HOME_11_X64'