trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install and build' 

- task: Docker@2
  inputs:
    containerRegistry: 'docker'
    repository: 'thsre/node-app'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    
- task: CmdLine@2
  displayName: "Download and Install Trivy"
  inputs:
    script: |
      sudo apt-get install -y rpm
      wget https://github.com/aquasecurity/trivy/releases/download/v$(trivyVersion)/trivy_$(trivyVersion)_Linux-64bit.deb
      sudo dpkg -i trivy_$(trivyVersion)_Linux-64bit.deb
      trivy -v

- task: CmdLine@2
  displayName: Scan
  inputs:
    script: |
      trivy image thsre/node-app:latest

- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'deploy-aws-ecs'
    scannerMode: 'CLI'
    configMode: 'file'
    extraProperties: 'sonar.projectKey=node-app'

- task: SonarQubeAnalyze@5
  inputs:
    jdkVersion: 'JAVA_HOME_11_X64'

- task: dependency-check-build-task@6
  inputs:
    projectName: 'deploy-aws-ecs'
    scanPath: '.'
    format: 'HTML'
    uploadReports: true
