trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- task: ECRPullImage@1
  inputs:
    regionName: 'us-east-1'
    repository: 'DeployAWS'

- task: ECRPushImage@1
  inputs:
    regionName: 'us-east-1'
    imageName: 'imagename'  # Corrigido: imageSource foi substituído por imageName
    tag: 'imagetag'         # Corrigido: imageSource foi substituído por tag

- task: trivy@1
  inputs:
    version: 'latest'
    loginDockerConfig: true

- task: SonarQubeAnalyze@5
  inputs:
    jdkVersion: 'JAVA_HOME_11_X64'  # Corrigido: jdkversion foi substituído por jdkVersion
    ignoreUnfixed: true
    devMode: true