trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install and build'

- script: |
    docker build -t node_app ./app
  displayName: 'Build Docker Image'

- task: trivy@1
  inputs:
    version: 'latest'
    path: 'td.json'
    loginDockerConfig: true
    image: $(Build.BuildId)


- task: SonarQubeAnalyze@5
  inputs:
    jdkVersion: 'JAVA_HOME_11_X64'
    ignoreUnfixed: true
    devMode: true
- task: ECRPushImage@1
  inputs:
    awsCredentials: 'aws_connection'
    regionName: $(AWS_REGION)
    imageSource: $(Build.BuildId)
    sourceImageName: $(AWS_ECR_MAGE_URI)
    repositoryName: $(AWS_ECR_REPOSITORY_NAME)