trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install and build' 

- task: Docker@2
  inputs:
    containerRegistry: 'docker'
    repository: 'thsre/node-app'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    
- task: CmdLine@2
  displayName: "Download and Install Trivy"
  inputs:
    script: |
      sudo apt-get install wget apt-transport-https gnupg lsb-release
      wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
      echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
      sudo apt-get update
      sudo apt-get install trivy
- task: CmdLine@2
  displayName: Scan
  inputs:
    script: |
      trivy image thsre/node-app:latest

- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'deploy-aws-ecs'
    scannerMode: 'CLI'
    configMode: 'file'
    extraProperties: 'sonar.projectKey=node-app'

- task: SonarQubeAnalyze@5
  inputs:
    jdkVersion: 'JAVA_HOME_11_X64'

- task: dependency-check-build-task@6
  inputs:
    projectName: 'deploy-aws-ecs'
    scanPath: '.'
    format: 'HTML'
    uploadReports: true
