trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job:
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
    displayName: 'npm install and build' 

  - task: Docker@2
    inputs:
      containerRegistry: 'docker'
      repository: 'thsre/node-app'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'

  - task: ECRPushImage@1
    inputs:
      awsCredentials: 'aws_credentials'
      regionName: 'us-east-1'
      imageSource: 'imageid'
      sourceImageId: '242451166731.dkr.ecr.us-east-1.amazonaws.com/app_repo:latest'
      repositoryName: 'app_repo'
      pushTag: 'app_repo'
      forceDockerNamingConventions: true
        
  - task: SonarQubePrepare@5
    inputs:
      SonarQube: 'deploy-aws-ecs'
      scannerMode: 'CLI'
      configMode: 'file'
      extraProperties: 'sonar.projectKey=node-app'

  - task: SonarQubeAnalyze@5
    inputs:
      jdkVersion: 'JAVA_HOME_11_X64'

  - task: dependency-check-build-task@6
    inputs:
      projectName: 'deploy-aws-ecs'
      scanPath: '.'
      format: 'HTML'
      uploadReports: true