trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- script: |
    docker build -t nosw-app ./app
  displayName: 'Build Docker Image'

- task: ECRPullImage@1
  inputs:
    regionName: 'us-east-1'
    repository: 'app_repo'

- task: ECRPushImage@1
  inputs:
    regionName: 'us-east-1'
    imageName: '242451166731.dkr.ecr.us-east-1.amazonaws.com/app_repo:latest'  
    tag: 'latest'

- task: trivy@1
  inputs:
    version: 'latest'
    loginDockerConfig: true

- task: SonarQubeAnalyze@5
  inputs:
    jdkVersion: 'JAVA_HOME_11_X64'
    ignoreUnfixed: true
    devMode: true