trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: docker-aws
- group: beskar-mandalor-group
- name: passed-variable
  value: $[variables.mando]

- group: ecr-aws

- group: ecs-aws

jobs:
- job:
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
    displayName: 'npm install and build'

## Docker
  - script: echo $(command)
  - script: echo $(containerRegistry)
  - script: echo $(repository)
  - script: echo $(passed-variable)
  - script: echo $(mando)

  - task: SonarQubePrepare@5
    inputs:
      SonarQube: 'sonarqube'
      scannerMode: 'CLI'
      configMode: 'manual'
      cliProjectKey: 'node-app'
      cliProjectName: 'node-app'
      cliSources: '.'
      extraProperties: 'sonar.projectKey=node-app'

  - task: SonarQubeAnalyze@5
    inputs:
      jdkVersion: 'JAVA_HOME_11_X64'

  - task: dependency-check-build-task@6
    inputs:
      projectName: 'deploy-aws-ecs'
      scanPath: '.'
      format: 'HTML'
      uploadReports: true
